import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='flex flex-col flex-1 max-w-screen max-h-screen min-h-screen min-w-screen'
      >
        {children}
      </body>
    </html>
  );
}
